// -----------------------------------
// FILMS
export interface origFilmResourceScheme {
    id: string,
    name: string, // title in original verions. but we hardcode change to have the same search index for all tables.
    episode_id: number,
    opening_crawl: string,
    director: string,
    producer: string,
    release_date: string,
    characters: string[],
    planets: string[],
    starships: string[],
    vehicles: string[],
    species: string[],
    created: string,
    edited: string,
    url: string,
}

export interface wookieeFilmResourceScheme {
    id: string,
    aoahaoanwo: string, // title in original verions. but we hardcode change to have the same search index for all tables.
    woakahcoowawo_ahwa: number,
    ooakwowhahwhrr_oarcraohan: string,
    waahrcwooaaooorc: string,
    akrcoowahuoaworc: string,
    rcwoanworacwo_waraaowo: string,
    oaacrarcraoaaoworcc: string[],
    akanrawhwoaoc: string[],
    caorarccacahakc: string[],
    howoacahoaanwoc: string[],
    cakwooaahwoc: string[],
    oarcworaaowowa: string,
    wowaahaowowa: string,
    hurcan: string,
}
// -----------------------------------
// PEOPLE
export interface origPeopleResourceScheme {
    id: string,
    name: string,
    height: string,
    mass: string,
    hair_color: string,
    skin_color: string,
    eye_color: string,
    birth_year: string,
    gender: string,
    homeworld: string,
    films: string[],
    species: string[],
    vehicles: string[],
    starships: string[],
    created: string,
    edited: string,
    url: string,
}

export interface wookieePeopleResourceScheme {
    id: string,
    whrascwo: string,
    acwoahrracao: string,
    scracc: string,
    acraahrc_oaooanoorc: string,
    corahwh_oaooanoorc: string,
    worowo_oaooanoorc: string,
    rhahrcaoac_roworarc: string,
    rrwowhwaworc: string,
    acooscwoohoorcanwa: string,
    wwahanscc: string[],
    cakwooaahwoc: string[],
    howoacahoaanwoc: string[],
    caorarccacahakc: string[],
    oarcworaaowowa: string,
    wowaahaowowa: string,
    hurcan: string,
}
// -----------------------------------
// PLANETS
export interface origPlanetsResourceScheme {
    id: string,
    name: string,
    rotation_period: string,
    orbital_period: string,
    diameter: string,
    climate: string,
    gravity: string,
    terrain: string,
    surface_water: string,
    population: string,
    residents: string[],
    films: string[],
    created: string,
    edited: string,
    url: string,

}

export interface wookieePlanetsResourceScheme {
    id: string,
    whrascwo: string,
    rcooaoraaoahoowh_akworcahoowa: string,
    oorcrhahaoraan_akworcahoowa: string,
    waahrascwoaoworc: string,
    oaanahscraaowo: string,
    rrrcrahoahaoro: string,
    aoworcrcraahwh: string,
    churcwwraoawo_ohraaoworc: string,
    akooakhuanraaoahoowh: string,
    rcwocahwawowhaoc: string[],
    wwahanscc: string[],
    oarcworaaowowa: string,
    wowaahaowowa: string,
    hurcan: string,
}
// -----------------------------------
// SPECIES
export interface origSpeciesResourceScheme {
    id: string,
    name: string,
    classification: string,
    designation: string,
    average_height: string,
    skin_colors: string,
    hair_colors: string,
    eye_colors: string,
    average_lifespan: string,
    homeworld: string,
    language: string,
    people: string[],
    films: string[],
    created: string,
    edited: string,
    url: string,
}

export interface wookieeSpeciesResourceScheme {
    id: string,
    whrascwo: string,
    oaanraccahwwahoaraaoahoowh: string,
    wawocahrrwhraaoahoowh: string,
    rahoworcrarrwo_acwoahrracao: string,
    corahwh_oaooanoorcc: string,
    acraahrc_oaooanoorcc: string,
    worowo_oaooanoorcc: string,
    rahoworcrarrwo_anahwwwocakrawh: string,
    acooscwoohoorcanwa: string,
    anrawhrrhurarrwo: string,
    akwoooakanwo: string[],
    wwahanscc: string[],
    oarcworaaowowa: string,
    wowaahaowowa: string,
    hurcan: string,
}
// -----------------------------------
// VEHICLES
export interface origVehiclesResourceScheme {
    id: string,
    vehicles: string,
    model: string,
    manufacturer: string,
    cost_in_credits: string,
    length: string,
    max_atmosphering_speed: string,
    crew: string,
    passengers: string,
    cargo_capacity: string,
    consumables: string,
    vehicle_class: string,
    pilots: string[],
    films: string[],
    created: string,
    edited: string,
    url: string,
}

export interface wookieeVehiclesResourceScheme {
    id: string,
    whrascwo: string,
    scoowawoan: string,
    scrawhhuwwraoaaohurcworc: string,
    oaoocao_ahwh_oarcwowaahaoc: string,
    anwowhrraoac: string,
    scrak_raaoscoocakacworcahwhrr_cakwowowa: string,
    oarcwooh: string,
    akraccwowhrrworcc: string,
    oararcrroo_oaraakraoaahaoro: string,
    oaoowhchuscrarhanwoc: string,
    howoacahoaanwo_oaanracc: string,
    akahanooaoc: string[],
    wwahanscc: string[],
    oarcworaaowowa: string,
    wowaahaowowa: string,
    hurcan: string,
}
// -----------------------------------
// STARSHIP
export interface origStarshipResourceScheme {
    id: string,
    name: string,
    model: string,
    manufacturer: string,
    cost_in_credits: string,
    length: string,
    max_atmosphering_speed: string,
    crew: string,
    passengers: string,
    cargo_capacity: string,
    consumables: string,
    hyperdrive_rating: string,
    MGLT: string,
    starship_class: string,
    pilots: string[],
    films: string[],
    created: string,
    edited: string,
    url: string,
}

export interface wookieeStarshipResourceScheme {
    id: string,
    whrascwo: string,
    scoowawoan: string,
    scrawhhuwwraoaaohurcworc: string,
    oaoocao_ahwh_oarcwowaahaoc: string,
    anwowhrraoac: string,
    scrak_raaoscoocakacworcahwhrr_cakwowowa: string,
    oarcwooh: string,
    akraccwowhrrworcc: string,
    oararcrroo_oaraakraoaahaoro: string,
    oaoowhchuscrarhanwoc: string,
    acroakworcwarcahhowo_rcraaoahwhrr: string,
    MGLT: string,
    caorarccacahak_oaanracc: string,
    akahanooaoc: string[],
    wwahanscc: string[],
    oarcworaaowowa: string,
    wowaahaowowa: string,
    hurcan: string,
}
// -----------------------------------